---
stages:
  - 'validation'

default:
  image: ubuntu:20.04

shell_lint:
  stage: 'validation'
  tags: ['docker']
  script:
    - 'command -v shellcheck || if command -v apt-get; then apt-get update; apt-get install -y shellcheck; fi ||:'
    - git ls-files --exclude=\\*.sh --ignored | xargs shellcheck -e SC2015 -e SC2207
  allow_failure: true
