---
on:
  push:
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run ShellCheck
        run: |
          command -v shellcheck || if command -v apt-get; then sudo apt-get update; sudo apt-get install -y shellcheck; fi ||:
          git ls-files --exclude=\*.sh --ignored | xargs shellcheck -e SC2015 -e SC2207

